import { useEffect, useRef, useState } from "react";
import { Minus, X } from "lucide-react";
import { apiHeaders } from "./App";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000";
type Box = { left: number; top: number; right: number; bottom: number };
export type CameraResult = { status: string; message: string; plate_text?: string; detection_confidence?: number; ocr_confidence?: number; bounding_box?: Box; payment_status?: string; payment_amount?: number; payment_duplicate?: boolean };

export function CameraCapture({ onClose }: { onClose?: () => void }) {
  const video = useRef<HTMLVideoElement>(null); const canvas = useRef<HTMLCanvasElement>(null); const stream = useRef<MediaStream | null>(null); const timer = useRef<number | null>(null); const session = useRef<string | null>(null); const busy = useRef(false); const drag = useRef<{ x: number; y: number; left: number; top: number } | null>(null);
  const [running, setRunning] = useState(false); const [minimized, setMinimized] = useState(false); const [message, setMessage] = useState("Camera is off. Frames stay on the local network and are not saved."); const [result, setResult] = useState<CameraResult | null>(null); const [position, setPosition] = useState<{ left: number; top: number } | null>(null);
  async function stop() { if (timer.current) clearInterval(timer.current); timer.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; const id = session.current; session.current = null; if (id) await fetch(`${API_BASE}/api/webcam/sessions/${id}`, { method: "DELETE", headers: apiHeaders() }).catch(() => undefined); setRunning(false); }
  useEffect(() => () => { void stop(); }, []);
  async function frame() { const image = video.current; const buffer = canvas.current; const id = session.current; if (!image || !buffer || !id || busy.current || !image.videoWidth) return; busy.current = true; try { buffer.width = image.videoWidth; buffer.height = image.videoHeight; buffer.getContext("2d")?.drawImage(image, 0, 0); const blob = await new Promise<Blob | null>(resolve => buffer.toBlob(resolve, "image/jpeg", .78)); if (!blob) return; const form = new FormData(); form.append("frame", blob, "webcam-frame.jpg"); const response = await fetch(`${API_BASE}/api/webcam/sessions/${id}/frames`, { method: "POST", headers: { ...apiHeaders(), "Idempotency-Key": crypto.randomUUID() }, body: form }); const body = await response.json() as CameraResult | { detail?: string }; if (!response.ok) throw new Error("detail" in body ? body.detail : "Frame processing failed."); const next = body as CameraResult; setResult(next); if (next.status === "accepted_for_vehicle_lookup" && !next.payment_duplicate) dispatchEvent(new CustomEvent("simulator-crossing-accepted", { detail: next })); dispatchEvent(new Event("dashboard-refresh")); } catch (error) { setMessage(error instanceof Error ? error.message : "Frame processing failed."); } finally { busy.current = false; } }
  async function start() { try { setMessage("Requesting laptop camera permission…"); const nextStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false }); const response = await fetch(`${API_BASE}/api/webcam/sessions`, { method: "POST", headers: apiHeaders() }); if (!response.ok) throw new Error("The local ALPR service could not start a session."); const data = await response.json() as { session_id: string; frame_interval_ms: number }; stream.current = nextStream; session.current = data.session_id; if (!video.current) return; video.current.srcObject = nextStream; await video.current.play(); timer.current = setInterval(() => void frame(), data.frame_interval_ms); setRunning(true); setMessage("Laptop camera is running. Accepted reads update Simulator Toll Plaza."); } catch (error) { await stop(); setMessage(error instanceof Error ? error.message : "Camera access could not be started."); } }
  const summary = result ? `${result.plate_text ?? "No plate"} · ${result.status.replace(/_/g, " ")}` : "No frame processed.";
  return <section className="camera-pip" style={position ? { left: position.left, top: position.top, right: "auto" } : undefined} aria-label="Laptop webcam ALPR">
    <header className="camera-header camera-drag-handle" onPointerDown={event => { if ((event.target as HTMLElement).closest("button")) return; const rect = event.currentTarget.parentElement?.getBoundingClientRect(); if (!rect) return; drag.current = { x: event.clientX, y: event.clientY, left: rect.left, top: rect.top }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={event => { if (!drag.current) return; setPosition({ left: Math.max(8, drag.current.left + event.clientX - drag.current.x), top: Math.max(70, drag.current.top + event.clientY - drag.current.y) }); }} onPointerUp={() => { drag.current = null; }}><div><strong>Laptop camera</strong><small>{message}</small></div><div><button className="camera-icon" aria-label={minimized ? "Expand camera" : "Minimize camera"} onClick={() => setMinimized(!minimized)}><Minus size={16} /></button>{onClose && <button className="camera-icon" aria-label="Close camera" onClick={() => { void stop(); onClose(); }}><X size={16} /></button>}</div></header>
    {!minimized && <><div className="camera-preview"><video ref={video} muted playsInline aria-label="Laptop camera preview" /><span className={`camera-live ${running ? "active" : ""}`}>{running ? "SAMPLING" : "STANDBY"}</span></div><button onClick={() => void (running ? stop() : start())}>{running ? "Stop camera" : "Start camera"}</button><canvas ref={canvas} hidden /><div className="camera-result" aria-live="polite"><strong>{result?.plate_text ?? "—"}</strong><span>{summary}</span>{result && <small>Detection {Math.round((result.detection_confidence ?? 0) * 100)}% · OCR {Math.round((result.ocr_confidence ?? 0) * 100)}%{result.payment_status ? ` · Simulated payment: ${result.payment_status}${typeof result.payment_amount === "number" ? ` RM${result.payment_amount.toFixed(2)}` : ""}` : " · Not charge eligible"}</small>}</div></>}
  </section>;
}
