import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import { apiHeaders } from "./App";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000";
type Box = { left: number; top: number; right: number; bottom: number };
type Result = { status: string; message: string; plate_text?: string; detection_confidence?: number; ocr_confidence?: number; bounding_box?: Box; payment_status?: string; payment_amount?: number };
export default function WebcamDrawer({ onClose }: { onClose: () => void }) {
  const video = useRef<HTMLVideoElement>(null); const canvas = useRef<HTMLCanvasElement>(null); const stream = useRef<MediaStream | null>(null); const timer = useRef<number | null>(null); const session = useRef<string | null>(null); const busy = useRef(false); const [running, setRunning] = useState(false); const [message, setMessage] = useState("Camera is off. Frames remain on this laptop."); const [result, setResult] = useState<Result | null>(null);
  async function stop() { if (timer.current) clearInterval(timer.current); timer.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; const id = session.current; session.current = null; if (id) await fetch(`${API_BASE}/api/webcam/sessions/${id}`, { method: "DELETE", headers: apiHeaders() }).catch(() => undefined); setRunning(false); }
  useEffect(() => () => { void stop(); }, []);
  async function frame() { const image = video.current; const buffer = canvas.current; const id = session.current; if (!image || !buffer || !id || busy.current || !image.videoWidth) return; busy.current = true; try { buffer.width = image.videoWidth; buffer.height = image.videoHeight; buffer.getContext("2d")?.drawImage(image, 0, 0); const blob = await new Promise<Blob | null>(resolve => buffer.toBlob(resolve, "image/jpeg", .82)); if (!blob) return; const form = new FormData(); form.append("frame", blob, "webcam-frame.jpg"); const response = await fetch(`${API_BASE}/api/webcam/sessions/${id}/frames`, { method: "POST", headers: { ...apiHeaders(), "Idempotency-Key": crypto.randomUUID() }, body: form }); const body = await response.json() as Result | { detail?: string }; if (!response.ok) throw new Error("detail" in body ? body.detail : "Frame processing failed."); setResult(body as Result); dispatchEvent(new Event("dashboard-refresh")); } catch (error) { setMessage(error instanceof Error ? error.message : "Frame processing failed."); } finally { busy.current = false; } }
  async function start() { try { setMessage("Requesting local camera permission…"); const nextStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false }); const response = await fetch(`${API_BASE}/api/webcam/sessions`, { method: "POST", headers: apiHeaders() }); if (!response.ok) throw new Error("The local ALPR service could not start a session."); const data = await response.json() as { session_id: string; frame_interval_ms: number }; stream.current = nextStream; session.current = data.session_id; if (!video.current) return; video.current.srcObject = nextStream; await video.current.play(); timer.current = setInterval(() => void frame(), data.frame_interval_ms); setRunning(true); setMessage("Camera is running locally. Accepted crossings update Simulator Toll Plaza."); } catch (error) { await stop(); setMessage(error instanceof Error ? error.message : "Camera access could not be started."); } }
  return <aside className="camera-drawer" role="dialog" aria-modal="true" aria-label="Local webcam ALPR"><div className="section-title"><div><h2>Simulator Toll Plaza camera</h2><p>{message}</p></div><button className="secondary-button" aria-label="Close camera" onClick={() => { void stop(); onClose(); }}><X size={17} /></button></div><section className="camera-panel" aria-live="polite"><video ref={video} muted playsInline aria-label="Local webcam preview" /><button onClick={() => void (running ? stop() : start())}>{running ? "Stop camera" : "Start camera"}</button><canvas ref={canvas} hidden /></section><section className="result"><h3>Latest local recognition</h3><p><strong>{result?.plate_text ?? "—"}</strong> · {result?.message ?? "No frame processed."}</p>{result && <p>{result.payment_status ? `Simulated payment: ${result.payment_status}${typeof result.payment_amount === "number" ? ` · RM${result.payment_amount.toFixed(2)}` : ""}` : "Not charge eligible."}</p>}</section></aside>;
}
